set(SDK_PATH "C:/Users/domin/SimplicityStudio/SDKs/simplicity_sdk")
set(COPIED_SDK_PATH "simplicity_sdk_2024.6.2")

add_library(slc_zwave_firmware_with_extras OBJECT
    "../${COPIED_SDK_PATH}/hardware/board/src/sl_board_control_gpio.c"
    "../${COPIED_SDK_PATH}/hardware/board/src/sl_board_init.c"
    "../${COPIED_SDK_PATH}/hardware/driver/icm20689/src/sl_icm20689.c"
    "../${COPIED_SDK_PATH}/hardware/driver/imu/src/sl_imu_dcm.c"
    "../${COPIED_SDK_PATH}/hardware/driver/imu/src/sl_imu_fuse.c"
    "../${COPIED_SDK_PATH}/hardware/driver/imu/src/sl_imu_icm20689.c"
    "../${COPIED_SDK_PATH}/hardware/driver/imu/src/sl_imu_math.c"
    "../${COPIED_SDK_PATH}/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart/sl_mx25_flash_shutdown.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/api/btl_interface.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/api/btl_interface_storage.c"
    "../${COPIED_SDK_PATH}/platform/bootloader/app_properties/app_properties.c"
    "../${COPIED_SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_assert.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_slist.c"
    "../${COPIED_SDK_PATH}/platform/common/src/sl_syscalls.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/ZGM23/Source/startup_zgm23.c"
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/ZGM23/Source/system_zgm23.c"
    "../${COPIED_SDK_PATH}/platform/driver/leddrv/src/sl_led.c"
    "../${COPIED_SDK_PATH}/platform/driver/leddrv/src/sl_pwm_led.c"
    "../${COPIED_SDK_PATH}/platform/driver/leddrv/src/sl_simple_rgb_pwm_led.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/gpiointerrupt/src/gpiointerrupt.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_acmp.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_burtc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_cmu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_core.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_dbg.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_emu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_eusart.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_gpcrc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_gpio.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_i2c.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_iadc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_lcd.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_ldma.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_lesense.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_letimer.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_msc.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_opamp.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_pcnt.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_prs.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_rmu.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_se.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_system.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_timer.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_usart.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_vdac.c"
    "../${COPIED_SDK_PATH}/platform/emlib/src/em_wdog.c"
    "../${COPIED_SDK_PATH}/platform/peripheral/src/sl_hal_sysrtc.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/fem_util/sl_fem_util.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init/sl_rail_util_power_manager_init.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_builtin_keys.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_management.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_signature.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_aead.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_cipher.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_hash.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_mac.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_key_derivation.c"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src/sl_clock_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_hfxo_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_init/src/sl_device_init_lfxo_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/clocks/sl_device_clock_efr32xg23.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/devices/sl_device_peripheral_hal_efr32xg23.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_clock.c"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/src/sl_device_peripheral.c"
    "../${COPIED_SDK_PATH}/platform/service/hfxo_manager/src/sl_hfxo_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/hfxo_manager/src/sl_hfxo_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "../${COPIED_SDK_PATH}/platform/service/mpu/src/sl_mpu.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sl_power_manager.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sl_power_manager_debug.c"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/src/sl_power_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_sysrtc.c"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "../${COPIED_SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "../${COPIED_SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "../${COPIED_SDK_PATH}/platform/service/udelay/src/sl_udelay.c"
    "../${COPIED_SDK_PATH}/platform/service/udelay/src/sl_udelay_armv6m_gcc.S"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/AppsHw/src/common/board.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/AppsHw/src/common/board_indicator.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/AppsHw/src/common/board_init.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/AppsHw/src/common/IADC.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/AppsHw/src/SerialAPI/SerialAPI_hw.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/_commonIF/ZAF_Common_interface.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/AppName/ZAF_AppName_nvm.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/AppName/ZAF_AppName_weak.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/AppTimer.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/AppTimerDeepSleep.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/EventHandling/zaf_event_distributor.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/EventHandling/zaf_event_distributor_ncp.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/ZAF_nvm.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/ZAF_nvm_app.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/ZAF_retention_register.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/ZAF_version.c"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ProtocolConfig/src/zaf_protocol_config.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/port.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_3.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/portable/SiliconLabs/tick_power_manager.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "../app.c"
    "../app_node_info.c"
    "../autogen/sl_board_default_init.c"
    "../autogen/sl_device_init_clocks.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_simple_rgb_pwm_led_instances.c"
    "../cmd_get_capabilities.c"
    "../cmd_handlers.c"
    "../cmd_handlers_invoker.c"
    "../cmds_dcdc.c"
    "../cmds_management.c"
    "../cmds_power_management.c"
    "../cmds_rf.c"
    "../cmds_security.c"
    "../comm_interface.c"
    "../main.c"
    "../nvm_backup_restore.c"
    "../serialapi_file.c"
    "../utils.c"
    "../virtual_slave_node_info.c"
)

target_include_directories(slc_zwave_firmware_with_extras PUBLIC
   "../config"
   "../autogen"
   "../."
    "../${COPIED_SDK_PATH}/platform/Device/SiliconLabs/ZGM23/Include"
    "../${COPIED_SDK_PATH}/platform/common/inc"
    "../${COPIED_SDK_PATH}/hardware/board/inc"
    "../${COPIED_SDK_PATH}/platform/bootloader"
    "../${COPIED_SDK_PATH}/platform/bootloader/api"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/clock_manager/src"
    "../${COPIED_SDK_PATH}/platform/CMSIS/Core/Include"
    "../${COPIED_SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "../${COPIED_SDK_PATH}/platform/service/device_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/device_init/inc"
    "../${COPIED_SDK_PATH}/platform/emdrv/common/inc"
    "../${COPIED_SDK_PATH}/platform/emlib/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/fem_util"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/include"
    "../${COPIED_SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
    "../${COPIED_SDK_PATH}/platform/emdrv/gpiointerrupt/inc"
    "../${COPIED_SDK_PATH}/platform/peripheral/inc"
    "../${COPIED_SDK_PATH}/platform/service/hfxo_manager/inc"
    "../${COPIED_SDK_PATH}/hardware/driver/icm20689/inc"
    "../${COPIED_SDK_PATH}/hardware/driver/imu/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/interrupt_manager/inc/arm"
    "../${COPIED_SDK_PATH}/platform/driver/leddrv/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/include"
    "../${COPIED_SDK_PATH}/util/third_party/mbedtls/library"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/inc"
    "../${COPIED_SDK_PATH}/platform/service/memory_manager/src"
    "../${COPIED_SDK_PATH}/platform/service/mpu/inc"
    "../${COPIED_SDK_PATH}/hardware/driver/mx25_flash_shutdown/inc/sl_mx25_flash_shutdown_usart"
    "../${COPIED_SDK_PATH}/platform/emdrv/nvm3/inc"
    "../${COPIED_SDK_PATH}/platform/service/power_manager/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/common"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ble"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/ieee802154"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/wmbus"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/zwave"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/chip/efr32/efr32xg2x"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/protocol/sidewalk"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/efr32xg23"
    "../${COPIED_SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "../${COPIED_SDK_PATH}/platform/security/sl_component/se_manager/src"
    "../${COPIED_SDK_PATH}/platform/common/toolchain/inc"
    "../${COPIED_SDK_PATH}/platform/service/system/inc"
    "../${COPIED_SDK_PATH}/platform/service/sleeptimer/inc"
    "../${COPIED_SDK_PATH}/platform/service/udelay/inc"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/AppName"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/EventHandling"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ProtocolConfig/inc"
    "../${COPIED_SDK_PATH}/protocol/z-wave/dist/include/zwave"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities"
    "../${COPIED_SDK_PATH}/protocol/z-wave/AppsHw/inc"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/AppsHw/inc"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Apps/zwave_ncp_serial_api"
    "../${COPIED_SDK_PATH}/protocol/z-wave/dist/include/zpal"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/SwTimer"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/Utils"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/QueueNotifying"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/NodeMask"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/DebugPrint"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/PAL/inc"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/PAL/inc/application_properties"
    "../${COPIED_SDK_PATH}/protocol/z-wave/platform/SiliconLabs/PAL/inc/hal-config"
    "../${COPIED_SDK_PATH}/platform/halconfig/inc/hal-config"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/TrueStatusEngine"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/Actuator"
    "../${COPIED_SDK_PATH}/protocol/z-wave/ZAF/ApplicationUtilities/_commonIF"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/CRC"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/EventDistributor"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/SyncEvent"
    "../${COPIED_SDK_PATH}/protocol/z-wave/Components/MfgTokens"
)

target_compile_definitions(slc_zwave_firmware_with_extras PUBLIC
    "APP_PROPERTIES_CONFIG_FILE=<application_properties_config.h>"
    "ZGM230SB27HGN=1"
    "ZW_MIGRATION_FROM_7_20=1"
    "SL_APP_PROPERTIES=1"
    "SL_BOARD_NAME=\"BRD2603A\""
    "SL_BOARD_REV=\"A01\""
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_PERIPHERAL_SYSRTC=hal_sysrtc"
    "CMSIS_NVIC_VIRTUAL=1"
    "CMSIS_NVIC_VIRTUAL_HEADER_FILE=\"cmsis_nvic_virtual.h\""
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "SL_MEMORY_POOL_LIGHT=1"
    "SL_CODE_COMPONENT_POWER_MANAGER=power_manager"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
    "SL_KIT_NAME=\"ZGM230-DK2603A\""
    "SL_KIT_REV=\"A01\""
    "CONFIG_MBEDTLS_USE_FREERTOS_PVCALLOC=1"
    "EFR32ZG=1"
    "SL_IOSTREAM_UART_FLUSH_TX_BUFFER=1"
    "configPOST_SLEEP_PROCESSING=exitPowerDown"
    "configPRE_SLEEP_PROCESSING=enterPowerDown"
    "NDEBUG=1"
    "NO_DEBUGPRINT=1"
    "ZAF_CONFIG_DEVICE_OPTION_MASK=APPLICATION_NODEINFO_LISTENING"
    "ZW_CONTROLLER=1"
    "ZW_CONTROLLER_BRIDGE=1"
    "ZW_CONTROLLER_STATIC=1"
    "RADIO_BOARD_BRD2603A=1"
    "SDK_VERSION_MAJOR=7"
    "SDK_VERSION_MINOR=22"
    "SDK_VERSION_PATCH=2"
    "ZAF_BUILD_NO=43981"
    "ZAF_VERSION_MAJOR=10"
    "ZAF_VERSION_MINOR=22"
    "ZAF_VERSION_PATCH=2"
)

target_link_libraries(slc_zwave_firmware_with_extras PUBLIC
    "-Wl,--start-group"
    "gcc"
    "c"
    "m"
    "nosys"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_config_zgm230sb27hgn_gcc.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_module_efr32xg23_gcc_release.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/z-wave/dist/lib/libZWaveController_series2.a"
   "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/protocol/z-wave/dist/lib/libzpal_ZGM23.a"
    "-Wl,--end-group"
)
target_compile_options(slc_zwave_firmware_with_extras PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    "$<$<COMPILE_LANGUAGE:C>:SHELL:-imacros sl_gcc_preinclude.h>"
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-s>
    $<$<COMPILE_LANGUAGE:C>:-fmerge-all-constants>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Werror>
    $<$<COMPILE_LANGUAGE:C>:-Werror=vla>
    $<$<COMPILE_LANGUAGE:C>:-Werror=unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Wno-implicit-function-declaration>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-imacros sl_gcc_preinclude.h>"
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-s>
    $<$<COMPILE_LANGUAGE:CXX>:-fmerge-all-constants>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Werror>
    $<$<COMPILE_LANGUAGE:CXX>:-Werror=vla>
    $<$<COMPILE_LANGUAGE:CXX>:-Werror=unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-implicit-function-declaration>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-imacros sl_gcc_preinclude.h>"
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command ${POST_BUILD_EXE} postbuild "./zwave_firmware_with_extras.slpb" --parameter build_dir:"$<TARGET_FILE_DIR:zwave_firmware_with_extras>")
set_property(TARGET slc_zwave_firmware_with_extras PROPERTY C_STANDARD 17)
set_property(TARGET slc_zwave_firmware_with_extras PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_zwave_firmware_with_extras PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_zwave_firmware_with_extras INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:zwave_firmware_with_extras>/zwave_firmware_with_extras.map"
    "SHELL:-Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r"
    "SHELL:-Wl,--start-group -lgcc -lc -Wl,--end-group"
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJzsfQlz3MZ27l9xqVKvkheLoIaWvMS+KV2KtpmIokJS1+86SqF6gJ4ZmNguFi5K5b+/buxLA90NnAZ6bqVyY3FmgO983+l9O/3fLz7eXP/bxfmdeXN9fffihxf//fnFzcX7t3eXf7kwmz99fvHD5xcnJ59f/M+Lr6t3bq8/3Zxf3JLXfvzXJ8/96gFHsRP4P31+8erk9POLr7BvBbbj78kXn+5+fvnd5xf/+qfP0Wf/xzAK/sBW8hX5N8RR8nxrkX/JU8X3n19kj3311Y+7wLVx9JWPPPqzFfg7Z1/9Sn93XFz+Grumh70gejbz504OhEIaOeQn+tgPxvkPxqeYUDTswHN849bxQtexHGI+SW0nMB5em49BdB+HyMLGl0f0gM2dE3mPKMLmo5McTPyURCg2cniDZc8YoIYjB7kmCp2luLEMDpD78mhGeE/SbSFuLHvD1PJnzGi3AK2WraGkdM0weMSR6SEf7cm/i2W2IbMDRP0H78y08Q6lbrIQyQGTAwTDGJlW9BwmwUL0mAaHk9nGD46FTcd3EtO2bGu5lB6xPEy3qIsWz5aDdsU86+6elkr/ccsDdH+OML65u749X4Ri39pQzYh2pHYP6aelqm2mxeFEPlD3Lp4bB6wOty9Fn2W5tq9vcNiHjp/gKErDpJIUb5bzJcf6SM7ED9gnVZcTJ5GzTZOAJkW0ZEblEhj2+TZAkU2fTKLAXc7ZQ2aFK/xF+3AC5geIkyrELLr9Do4XojtodMS7T5vX5s5F8cGMD2liB4++mcYoWqovJUhhWECEHNdME6fbcczavsU0CLIYqQItb3P65rvvF6z2+hbFujKH1boyB6GuTDs50CqZAAnRXLC16FsboBUhgl5U09vI3rw5PUOqyQ3ZlKBokuYvCfw1mDZMyxB2sb0K28LuANVtUnSIdsSEae2UZ0ymQVFypKdmnS3OsLI6XLJ32MtrgsVKN8PiAD3suc42rw1svE33C3EcMTvsx9jFOEwcb8mxFdPmSA9qi+3EXaqLxzTIJ1e0ootz7NkdSWpqFZvRfmuGjx6tprK/yb+nC6a9EImRIeFyY78+nR+NfB2BvaqAyPhwj/2RZYW8oSgnNmmP68RSpKMgYwxaHc4nZJBDTKKEDsOS5xAr83WDI8vmAMObuwvzPPDCwCdD81g5ub65se5m8ZxJpCA3UJdNG65jGhUbaFhuYN3HS+RBttVhlvm8ywH5toujJbzYMyjKbQHn9QwOcnM6bZdZoCzgwTHT4nwJqB/vgshbkzmTxIiGbD1oeX+zzXJ4blPHTRx/Lb7D5qX6LY4fJ8i38CJ1F8/+ROYLVGo8+wPMXce/J4Mx8s2Jaytm2bE1wOjEiqrFS/KnYk49a2L9v7iya8b2vbk53Xxz8uZk0+oPtl4IXZTQaqbxRO+Zd1nD2Xqi98ytQ8wG/nu0jTsP9h79/ZerzVnvoT5ikEY9q+WTzTz+HCdkWPxl723OlBXFAb8apfuM3EdGww1GptPIZRhdlgZXVoKiJA2119Wl2RfWybGDCX7pW25qC6R4Zus03m6+PezVNRvTXVMIMXo8uYlOckjeS9VYVYsjPxs3872+oro0ubqyJ01keaHGqtokRTUp7BeASer2HUYVbdMIedprqliKq0qsY1CVsxRUZXmp9poKjoKK6KY37SWVJEU1EVR/F+gvq+YpqsxD5K3YipwwCdTN+oAJ7NEV1Rm6rv7qCpKCmvAR1B1Yqu7A2RYZ/UVVNAV17eLI0r/2qFgKqtqHZKSuvaqKpbAqR/+kKklKaDLD4AiKVoupoLrD7hhKV8VSWNXTMYh6ktHkbPSvLwqOoorQEfR2S5KimixkHXSekunSFNR1j59jC2k/g9bkKajMtdRtu4NSVXAUV6Tw2CCgpu6Bw3FVZPyiv6iCpISmpy3Sf+zYJCqpje7kcfwjmChkERbVimPsx/pX+w2ewsqyjY9HoKziKarsKHq+rmTP1z2Gnq8r1/P1kONugyftZTV4iioL0WF7DAsOTaKi2mL9O/cFR0FFoeXrPwlQkhTVtPOewvAIuotNoqLaIv07HQVHcUVm7Ox95B6FsiZXQYWxFaHEOoRI/0FZm6qoPnwsrVmLqai6I1hViaVWVeLnWOWZNzBRFU1xXcewJaCmKajrOEYrsmOV9DgGK6nsaOU4lixlVywfbKR/ySpJCmp6tBWeDoLSVJIU3lfK/JrxJeurbog+zwv88X3Pjm8x9ju3t+CjhLhyxdyT6zAIVaPFpuvS3lFBZ8Vy3CZdUOExtrzYic0gC+1DX9eFPosXV0tgY9NyURw7u+JYojZy2NQ4ihyNJQ1y46US9tMVZ3rayVJy4XEmGvGaTXSnPqrY8EuEVmVaoiRHKy4jdFlHzKWCfkwGJ9Ymi1RkuKwTlKQrTqN0aFdsDF5npH+QKxLoV+QlZ7WzQYVaQtVosREpD/Q/CX7ydGHf5cTNaXRLguuqO/wpyb/JR6xs60K8JCNfRpIgcK0DcrpddKFO+mAMwjz43+p1SCWurE169BgjIqYiXaWIadhblhlG2MkHhfpp6fPrFT+wAek2CBI3QOSb8UFpO0TkeDvSfna9WqHW1olwafQZylcVKHTG3dCK/6WJFxyjx2q0am/HMIuTIEJ7TbU02Y1qagblaWSC1aqBjqhhetyUwlEURHTUqY2YHivx3KaVhhYriRIToihec6FhtMDU5CbUAXpKarDjaopwjGngsDUPHTLEtGlx2yV+E0+E8INtZNGryvDDvM4vayTJGJM1IddrMwr5RotONUbrcuT2Hp32O+YBrXjocUzbAFF+97j3mhlvjiH5GlSF+ssTx3TtLKNZ0pdTcl2OstlaT10MklNHRr3EL0L5gdaAZRRTSnr9EtRWWBahLkd+/VC8QTqmTnjAEalW9JbWJqqyamj5cvUS1HFKUTV0OU5Jb72ltYlOS+88mKdkkpt4F51tnvZrBtca8FCup5v+bcLTPJXjSbiqTp6swdbXZ4UyZs7qU4duiGhMWZhJaEaQWl0KMOXUKb0dmsLVU3UbnPbihgPj8G5P0V7a8Fn1MWnrHkYSlDZ0GEmslpTqL9YXG+ow8Gr6pd2x6vKUz9DHILDBUz5bH4NAd1jg5Easec8gzFiqibi+S5tsSp92GfJzS+s2Rl0mWnjSRqZZGLMKrTezeVpfhwEEQ+QIV5Vjxlau0csvRSvYZSiZ6lqK6lMEq/p614KC1H9O/7rR9R3bo1QVJSZZfoXYv1J19T1dPK3jnGFrjvb+g06EdaZP813iPlFgPjhRkupQ9/Y9ScskohtimGylwn9z8pOu6oe4gtVK7etoYbpkbcz1i2ibT1k++yxFd7lVBdp+Jj+RTEmXZqOHfCP/UagdYi7QhPfurc+2puupeoStdFpHOEHRHq+4mVUqgZt0pVN1/dpQKDlldqZWjgmDQIOFKaE0LKlOyKv746mKarIqh1OaZ/D2xus5+XvtPeUyAkd2mE/v0IQpUC8mTDUoQWFaFZucj9JCEq4Yf6MpucwtITPWxuS8EQaPJNOB9nVbkOvnlxadMuf0OPIrldYr+f3KxyCuZiorUZdZVgGNUvOs7VfDyCGd/RU36Y7JHCGrstJrlw7NPFNUhD2O00rwEYirmcpmbj3VMUiCNWf5TWIw7VhxK5nSS7qFHZmTaZw3bVLjZ/3ihXsc+ViDsR5TTU1OZd3WdN3qxaPwQ3livU1NNlX1VFOTgyvkLsZhFvALqKBXeBqUjIpLfUS7yU4gU1TP592iPN6b1sI6RKU15tfc6S+x4imt8AhyZ5unQFel/aoG1VdXHIui0qapLuk6OaMKA9NkJ5W+Gsrp0gNrnFIbu+gZpmHKsdYv9jmPssjXrPjVWP6siSLv4Y1HozWc3OoopkNQZSEvvLd6iSjcUBTumpW6+BnnV7eXt+NHa8+DqH8DufBF5YztHFbgheTLFWugTLVBhVWhNfvUOAUpf+GB0F11HWNQSoMZR0nyhej2E2JRKxltWkKpQasKnSS0WPEUZOG2vLMV74RnKWiy4ijwwjSrs7/TSkGLFViP4ubu+nYDWisG8WZtv2WiOpm3oMVJ+iAmo4w1D42yBDRITes83AZp1As8wdJOp1WcNc9IN+XnrI02LXU9COzZ0QMnOAcravSUrhpeNzhQJrUZ0RIPhgWaWq/Qy22rnZQAA5YW3nr5M/dci0zW2e/RU9bLb1taOQu1HUFzUo8eWI7yH7wzgKJHYeiVgSh1V3cf5ZJ5rUuK00rRx7XiLsjZ3GMfR2vGy2f5vUFKRMOq04ks/mIBhcpHzZ2L4oN2CmpaIjrWDezBkjAUxgPsWHKziij2VZuu49+vOXPfcARtBMcpyuVPrTS1aAnnT60kDIUVEsufrrPl5U/ySGbo/OrsLJspQBrIJ6QMFjGVo4i+r2Tjv2PPRJYXrpmBqONo3mlQGY3jSJ5beZ20xXlwLbRL2vJW3HTcolww4RKmlzxowrigwqNsb1fcy9piXDDhEcbaZAoslilwfuWZJpwrMjza+9CKdKkxKi580k6gDeecCo+ys9HFywUTLmFka8O4oMKj7Fq2JowLJlzCtod0YVxQ4VLGMfZjXZq/Bhs+8ZW3WHWID26k6hKnF67rQbpgwiMchEibjnPFhUc6uwNeD84lFS7laMX7RNqMI/7FSOSxSJs+XSTWp9OmnhOr4vIN2bpQrsjwaOtULwvXyjr19oU7+9kFxnpwLqnwKGf3E+tBuaQifz0S9xbjcopnxel0KjRbhq6piM026cG54sKdvDk4uvi5pCIyQaYJY499OL1PONv9iFZd3W3zbhDiXODomPr4vM2G5/e1bx5u1yJiFw9nZXfFKNydWoR/uVg267ruTcntvC12UTLt9SJvl/q61NgNNtx+y9obo1vERzZDM1cK9GAtdDN18ZwOe0Q61Md2iLAWO/RgXjARWezQgzAWa2iK9QVNOFdkxGjr1TXpcRJbsdGDfMVFaMVGF84O+/ICxoqNHowLJkIrNpowRuxrPVgrNnowLpgIrdhowrigIrpiownrmo3oio0uxIePEjNWbPQgXTARIKxXo9gmJLbgpAfziovQgpMenEsqIgtOmjCOhMbpkTb96kisX61NNS1WQ8fa+DcW9O9zbO10GRzWZAQX9rShXZARo63ZZEKflNj6pB7shfsgOg3Qhcfn2aKgHpxLKkLrk3pQLqlw1yf5O+gjRGiO76CPkOOarDMJ3fjDbrp3+ud1e8/taEZJHJd/j0vsmuXD660MZx4ySicYuUqj5GV0OPbPq4xoWi03SWhinxEbvoqmnSXQSyvwi2l01m25/RMd5e2yzIf7vsw0UKJmiEwrjR5wbL76xt6u2Iayndt2hVHpNHgiWDlKzA+b078DP1QipvvhFYUwvzn75urYndFWwqxrhkpmx1UUs7acX+qsWx3b8c4QZW6Vy3xR75wwRFlIK80rZvIc4uPRyqIsrPW4ZI4qFG1YG5VDK7448/50Tj3ZA9CtHhjjaghoEemTjWJolrFm+UMm24kdVx6I09PxMSWljSOLYDwlJ84h8+w1b6dPV6pBv+QlIiHfp2XiKAroZXE2XnGSd0QRm6aIwKwB0VJTxUxExg6jJI00VdIkNy28QRgFSWAFrPF/58mtywqjxnIZeVIbb5X6DELKaLKb3tw7GOPvTjevXn8j6I/6Bf3cUnMzGFynO+nR26ZDcwxd/2TP6ueajJbRZjjdIRlDQYdkz+rnkAzTaDOc7pDYsfEjcu8FfVI+rp9bSmZGjyd03+7ghPx6OhvQyMzuPYnM7mXaKAEzDrHl7NZcWOo2iIRVPltTzdk8GWy+UpM0s9IKpUmwxwIT8ERBxjXCLkaxQA1RvkCGsztnb37Ze5uz03i7+faw99eNPtRJl8IFRkehISKAO0osQbzATl1sVpN1FKC0dDSe4ImYV49MWooKceSEBxyhbs9QNqITGQLrcF1Orae8oWDsbhyQ04VtG6vVlg3lxaUEbVacY1mNp1ffrDYmRXTjWo2hW8owmclp0S2FxggCrJfbkfPQu6ys275iux/cWqga6xcFgrVeDZaLNXI9ZSVWMOJfGBM+ehrSb7ASuLqLmsBmtN9qqoZNUOWlN9TEamW97YOiQi4YiWdIveg3WE3KkHqpYRNUFwE0xhYRn3Rv6epdM5m1AoGPfX54fNI53mI7cWMzTsMwiFgLar0lEDquEFl4cypwZFmkux2hZNXzrqX/jKaLjL4PjFyiMaZAYJ2tfjnwfCeM6BmRVS9vna6+I0BIfBijI053FvsZk3HM/k+/yisIrXl1nqCrija5QVhk5Zl61Yqew2TFQJeyEtuchbP+kcnskp6xfsPsWg3ndf2rhaK5bxDm5gKESZOx5jUgUuIabLnKLMs7ImUNtnxlHrKOSVqDLr9WwsXOGO84+iBZkety5qs8oFdHlIJNuiLaNq/fHJe6BmERfa9fbY5LX4MwV9/+qOrNvUS9ia0/QnSPj0hdhzFXYXKIMLIdf39EGnucJfvnx6Gyx1m2f34sMrukRVPzAbnpmrvrpqRmzRl4h0eBz1zXYD0uNmrPkyaJ/BVDug66udbbGuiVbIWLS46x8pZ5WZUd0rJiixiExya3pi0kmHSzi3Mbpo1D7NvYtxys4xwUQ/YIeVHxhde2qeMmjm/e4+fj0T7AXVI6ea050joy8X32E+STWt95yCd6j1B+m72kfES6iccmuuQsKdVbM1D8NKUeO6A8R2js7P3s6MKxyW0RlxRtZXthjk1xzVpULmHjE7YRQT9S6aMKZrjhsOr9rvOdcBi8CFbYBUdVm4/wn+GCY6rlh+lPccCR9mTGJYg6IgjR39KjbOqZzCVlH2nSD7KflupH1g4OkZ8m/qiqfjZ15bsOWBMl+s2NNlzWnP3t0Zad0Fr/sPVEyWMHsYcKB3Ne6CiEj5CfMrY/Fs0dztNGf0cmtmY9b9LqyGT32c+bsjxC+bJbW3qzQkem2WNHHuV0behdSjSLHE/NzSIuKXrl0C7TBI9EfeEPXI8vmQfZT5F/XAnOZA69Ul/u/YNbpjdrTO1GSRWz6qxbi6vIZo/6jZVjCMtLlAoo3HhN09H+mFKpMX7zRYIcBeHzUYltcJZUq+VE/phUiZn75muaz9qNKZ40ZdcFOCDfdh0NN07xlDeJS+rWd212TLTswmzzXZQkOE6OL4t3eIv27MrXPeS42+BJe8lDpGX1BjFaMerpFLEl4ylKTcuLndiMkiBeMRrzVNVd9uqP+zV6tPp6qzzY3+IqWdvZeOf4Gg7nRlQ2OUuq1XPoOqZVZqKiN0g5JqHDV5qM127arhJ1xQ6ylkxZx09w5JNKMds/q7vqUeayaV0CaK96kLXsnMEBW/dFbETtRY8Rl9V9hIona9VzKXBUq8w6IGuO5ZjENjhPmRc6Jqkl4XnzQsekeNLS7uD0yrEpbxKfPC90TKJbrGfMCx2T5g7vqfNCukseIr1CuOQDcplh54RiBneRXg5GsGulWv3ky5UHuZX6LGFqXgaLIlj4wf4XXU9GNtXS8mP3UpOAPDQ/wnUGs87Z41KlkXEoJ4nbhHghnvOnSUKRbo9r7kNn+bBgYzK6xNTE6m7ZWrwsdfQXdXqPk1hKrnJP2pgC9mVnymI+O5a3OX3z3fcwUZ9LtPXKRLnFpSBSlo4mMZVRhis7q2WprgOKzNUkxg/XWz5NJ5OXbyxFtVTspraT/UT2UqCC4KWmbXnrlwMvrYpATUkgA5CHd2m8/Lo2R0DJSUyBh5Llt55wFJScxBToU6G2VSxWn3rp+tUPkV7WPDkdsPrGe9q8Nncuig9mfEgTO3jsX4MkWP/0YoH3oc00Rsyo4H2/M95ePQsyOFWhi4fEDvwodT5tXn5Wny5rlw9WupRhdmXTZZEpCd5omC62jo2Ek4NDOuohkcEJ37+LMKbbMnhlOtvAwc89t0EaWQLXnuX7QehukKWLLPWc0XCPUXrAyDgZuQKjRXD6dpVL33JTW8AhJQtzjf09PJ8UKowuSe5UZPWCFwYrDMOldVU0gWveexz5WOBWXhqaEA1fzdsuag6RHPjv0ZZ9M2snKRLHum9fWq5R0cv9Y5TyjYY2g01c6u7Hnu9+OT8f9Fnrwbc3V+b51dmZ+eHu94E3eu/4gW9mc97sZGSkDdWtcWoQbxlNRxi1QqOkzkqPAaUoXn7QCSe2YC+h10NWtHzkVzjFFX/JND5exQX7Ib0j9cx4JSRcP11h7wr57FuPuutGGIXmmcYFqtBi1EQh7u1lDW7EelooIR5Z/jwz12GFAKPmx79CIgoIrL/8Er6wmCZDrhwbhxG2UILtfIews84ZXWFxw3z5Qewf6HHWPfFOqLHALkuurJ8J0M3d9a2+kpoMBa6ljpdfeROWUrLjyvBwHJN+s7lNd7sVNioKC+rz5EsLUzOMgiRYZ8+EuLQeTyFpjxEKQ8Jfb2FNllxZZb9AX0lNhnw5UfDHKiuQ4nIaDLly/pbiVOOkqegJ3EDlhQeN67qaH19Kgqx7MxuFaZzNuiy5sm7pC1eaq+qQFEirCCNP+5a2R5N/JxGK7/XVU7Ljy3A8rZvTmp/UmgNrTKjdjECTGWdrQWvgoZ2QLjuOmKyfrp2IkhWHfN7iase+osXbo9Kq6LST0aPHkUPrOQ0LREWLRz+v3fTjX/GC2zaT3zfGW1Z3nW2Eou4afb9SD3zSv6IB0AjT9f1XiDMK9kaPHi8flJcF6ielRY0jozwxoZ+KJjNBEeuEcRNWMhK0rS0nRroqaTDjiECus/dXiTTLVdGixpGx9U0v1WDXR1dDzYsnAMX4zTfrRS3gK+kT5EkiyZd6phWscPCTL6dNTkyKFywfc1xUScFNWIgZoUedxZT8pASR7PmAYudB3wzHIsqRmEdQyKa+9ZPVIceTss69FAK9yuGLJ4Z7xyY1p6MYFkc5Ydo2Q8M8efM8VlgHFVrjsnOuNBZDIVG6VnlddjwxefAUMwxcDTNelx1vJs4LEg0mf7sqKloc+p5NQ6Trx7/mxRegZ4PZIMaTEMZrXeTEV9HiJiAER1GgwSoVS0dFTUAGnbHRYbWNpaPmJiCEmLM0bDJa1HjzL8h2A0uDpcLe9EtNjCfhXuOuVoccX4qeFW6DGFfCY+QkGpaKBjHBOUmdsxWLIkdWRN4hPWLzgF099qh1RTEI8pYLY9e08Tbd6yuKSVFAluU6Wk4ot7kJCPGcWIPd+ywZJTMBEeTVV2cajxLZHIWFrRLZWELUcPziXsVtRc9hEpRZVMtVpR5FoblL/bSM3VY0OPmqqYqKnHAW009Jm5t4WVnlZmiZkjJy//NQ8de0yDApissqLsssN/CbfmBmkUaXv8xeRukoa3HxsRskzXtRdZbM4CohNAki8qLeAmuO4sKwpWH93+cnLmi3s5ePBiajqCQoLmmVu/VkJA3fpTckid4trLOigp+4oBDd6107lATFJZGxv9aKCn4SlbjeKSQU87C4VKTor6xzRQi//84mKdn91U4Wg6B091dnUWNXmgzK0nIXHIOgnCRtFyiHeU4esmgtksEVYmx2RJLbrOV69jrLLPhJ9ux1VlQSlOzZ6yxp+DakIUn6TsgPkJSQpuPOpz4/uVGYzoIKfpKjMJ0VlQQlRmHIJ7w13ZI7zFNumKm1MKF9ee1xnM56YskM2J031Vpbn6v8HK/WAmuOkwPyD8T4Ezx92/Mg0iFoVOmyKqZS8RkJRopCkaNRLdRTUbDjy4j9VxrLKNgJydBsyxpLy8jmNeYpSH3V1Pz4UrLzXhpLqfjxpaSOS6/i2mkQWnhQTosjP5wp+cd1da7Lmgz5ciyNc1pBji/igMj/NqcaK2kwFJQTBu7yV1hLCio5Ckha8Yp5CVGS98nrtuTQEyR+hbql1VRFT8jgREX/nHCIkpebk+XvEhYX0+IoIInmRxPZf6RxYrp4j6zncsubxhpHSU8TvYsCT6/ThUKym7QlhdOBafZ6DnUswhm0JwiPU7o6g5MjFM+gLumAONZoNnJccEFVUuDT69Plr3edqLDkKirxGOooiQqpETdNZ1VtmnxhSWTa0Vbn/miDocDFFNtUYy0VPQEhGk932oLTnfZB43F1QY5/AYil036AroqSnYgMnevjip6AkD/0Wn/tS/ljeP21H4FGZyEDW2fYkWc0FlIT5IvRK9JGT8pwtI2OkL3Ok5p7wUnNw72901dFyY4vw0OW5t2sFkX+fUuext2Tghz/3p78ee1nZPs8+dI02tfekzOwpb0n4bXOGl6LicBeED0XYeNN5LqBxvPLA2S5In2cmHFg3WOdNi52xXVI8kU5cWLeaxTjtSeoJsgVEzga1wcFOa6IEGvcoSnI8UVoFHCrp0HsZp7w3opfbXSWUfITkqJxK1PRExLyrd5CvhUTUt6HoK+WBkNhOZrPG/doigvLLkrQX1hJky8scJ9fnZ3qXCs0GPLlRM4DSrCJLAvHGnfP+jz50sprOvQV1WDIlRM5pA9hv3qj8QauFkW+IJ3nmwePW3QjpR2QxludS3YiMjav32gtpOAnIuVMayFnojJe69yLrvnxpei8S0N0X0YW3RJZB417aS2KYoKyrY9x6iQ6LyezmIrJC4J7R/cEqzgKSUocOkWlt6SaI1dSfUmftopaFPmCHE9vNRU/rpQHwtfRKfhIV0uDIFeM3hvphLfO0QdNK9K4PW0yFJWjcX3WZCgoJ9Z4e0CTIeNI8vC95K1DuWTcyj+Qq+vme0LekNljX0Tayve4opSGjPHR1sUarpjU0ob4SsotdsHe42di0YnM5DnUsaPY1z1IfJoD4mc/8J913NMwKL1J+aiPoFKFssdPc4fQtxLHp8HJwiDWc4zTSD82XVmxYUR6eInzcCRi23RlxdLyTdolOjWsZU+VIbhPWVR0fiJOa5E1RXFReu6taokSP+raCp2nW/BGhrYeU2mJfkLoxMdSx47Tnir+iKohPvWpTjiShmectqj4jJDWOiuGopJ0PT/a0CRzTrQIdKftdpGGLKkdI1X4tCIna62sxVJYmvNF8zqkYigsKYlSS++uW01RVJT+kwHSo/4H5Kaaa6opCs/fMb9mfNn7qv9FZx4wCpLACtzWZGDnmS8vqT8604WdZ35/+3NvPrHzyNuQei7rpHwi3iItNmYFBey/9YH8xZ+sJAzM4mHzEaP7xW9oKF1p5P4yCCGDpdkoWBosxtxs3nhp8Uw+R6FQGW56xH/wjisJC8LT5+QvHrCf/Ip823X8PT/Df0E7E9NXTNshVb+zTZNg+VvRhF3WUmcMkufmEfab2hYFEdkiRYP5pumvcOkWpPRSwAz5x5zypYDpdUYx73PZb32Zlet59nR+sfSOOEDfzFMJM4Z4C7UmvRe1zS4cwaLNZ/Fifh/1kamtSU8vEHdRim8TlKTxhb93fMGO493thb6+6koyGoynO+qtlaSI1EGCPeviaX29VDI0unSlXNSQTazcOR6O3mEc3rrkP/pWlkyqnHj15Tsap2iDoagY7ZNIIGVoBtZ69NMgKCbFRKHGpadDUkBShBPSkyMg5K896c7pnPGG+XKE4gd6AYa+1UPNTyDFzj37Y7p1nXiNOMZSadVlKiBunWlcKVUj87g9OfSz6diaK2qy5In6zSTQdmol5AUTr3Hrgbg0Jle+wLsI+XEYRMkttj4WxrRWOURYQuqFb4eBs8JNRpN0NtkKlMIGXjaToXlxZNIV7GhpLawgKNHR0l1OSXJaR0trdWy+AkLLgzBadyMbJCUkaZ1gIweQxK5BK5uO82yLIX89M44ssaWdUka5eVGHnNEWaxAtxgDV6fNSjj/RQTrks46DiBamg1Qs/fccSdcZeGvywpf4fWFsAWCkC+lv0G15UeC6NL5c6KyeKtQL1SaML3lCsUjyJ9d/01OLIHkzxhbhTkzomypdiiKy6MDSxrv1e6dsSU16QnLK3rrGydTjKCJsi2In1lhUi59QeXom3TvPjBMUJWmosTI2URGJqO41NRJdn7VUtl4B1kLp61J+Gidrk5+IIMr5DsXLR6cU09OkJyLHclEcWytEQRbsYTToTe8MfwmRK9AbJk+Z2yBI3ADZGgyR2x4h5AwGQ/6WH/pOnK1766qoZiemZq1rFATlyFyikL3g+M76k58DYkpuYko8J14+bLegkpKbmBIdJjQHhAxOZbJ0hMEjGZ15yEd7fau0HkkxbREiHHXVVJGT0JLFwNS2mu5QFNSl39TzkDzBSWeWyhStELpHUFfJTUzJI0qsgx2sPw84oKbJb97kX6+X6Dpb5gxew0Xkkd9/I+zO64kv4hMHx5sTpIO/CD9jnCNnxYG8nLn591+uNmdaaWrTElplEJneLY+c8qZ4bx1COPDfo63Yaav418eBEYfQOkbvwXyj78CznUS8fPvufPWFjtKxRsNzRu6YbMUjF2SUXFm1U0/YNkCRfSzKKrLi0khv26ZzLhocQJIR2aYtJZcMLo5Mac6YLXJwPoJVoZA6GblvP16KlenqcfPwqL3LKrJGl7a038Z+Elvx7O5xJvXN2n2bMf/Rxc6C44Cz+jWi7noqlgKKEhTtcWJmr6w/FOIp67EVUEgoYJ9ul8hfM7873Xy/fAgVWaWDrJnjisGJWcEZ249v34t0n8bKfOvB5moGUR7iaODcPCO92O/qsl+CmW7EfVmisakPfM2J7yXXvB2Q+9Ia2szDcHL9vN4erXkabcqTXNZwQHt9UW8n9LkKVHvVZEQZmJMw0lvmEGMBsbFr2pa9/lz4eDLWJCEq8clj8IHhslBd362paT9zbac3Ws2aEWfipTuQ0kgDg5qgGA2WtRg62Atas3IvL+/mQnwrzKbiSK2CQoeXmVtDJx3caLBUGF2aYH49pxEpfXoGgTs395idCeU69FGPk7q1MKOgZDSocYpW8eR7BzmxBrvCh7U0GE7bEk53mLPnWpvucL7g6+Uvvh9xQ0bbqHlx0vPK8TdX6Gn5+624EprMpqXgf6Q4xR+CxNk9s0MxtTzRflonf7SZGX2i09zzIbDxFYrveY4pn9PJJSUno0lumhve4W26/xg5fn+bfccR9ZM6uaJmZbQJckp+/fC5HuNenqbzwbGuWEKf35zzUpg8opMbCB2joDRNcnaG8l0dqYqnv/u8Ts7ocut9Md1Nt8++laFxm/vyQZ0cU5EyWvSmueJqt78L7rHP7flUD+rkioqU0aI3dUzAi8Pa/diabhoUdhK74VaRz7hWDRZXOkvgk4Y0v9hF1epezwqTi+XZ5oGG2yMWyZMPJBHVrUYPGeMyW4TRKBO67GOhEG2Lc7BKGbGMDTGL80k9hXRqC8Mcmls6PVojKuXDsjbMbSlWonyinVoeOf6w/fLAoFoWTStsLoHnLRBTs2+GyYZGWNgi6z4NzQjHpHujjhHbFJNVPvGGQicLnKNuI0jPzFC7pbK1GrSb70FWZblCZ9p+cKIkpYdWsoNj6lvtEXtMfh5y1MW/KMEFejGqeqU9K/y+gioqXSNCLY5CMl07oy2OUh7Rbtx+1RYoZdG0ItLiKCPTMzPApt6wnYb0uC22zV3qq1tFHrUo2iqqIsc2JdIqKhsQ98wMtooKa7/R3Bz4y+WdAWvsFMpar4WoDRkb6UuootI7LSXUl1DFZsQek1+1tquMUcsCkwMN/FPe5Ku61RiwxeQVBnGS3cZ7Equi0zbBZHFz8fbd1cWJZyui0MCv7OceSqNs/2C9mrFDqZsQGi7aYrf1Tbbx4jy7EdXJZjCe6R6RyN68OT1DP5ye0P97e3pKnqSXPnUf9Kz0BEXeCd5FZ5uTL/vNGfmPtzk7jbebbw97n7yWBIFrHUjftPsuqaROYocwik/i+IQ+duLYOIOr3jnZ++mJZSc/vNqcbE5enWxON5tXm9PXBDe278cQ7fuTOCEtFPmC/P1DOUF6Yr589ebN9998/82r168a07g/2ji2IiekbvvTj0bzUzmd2XJt9u2PdLr1D2wl2acXX7+4vbz6+P7y/PLur+bt3ad3l9fm1fW7T+8vbl/88OI///vziwh7wQMm6fXDDrkx/jq/0zpx/Iun7CxdTH75z/+qv74N0sjKvxWYNKUveoGdupi88PnFjwW5H66usi+/evJcP/6h+Panz58/vzgkSfiDYTw+PpZ+Iy404pgG+aIPnWCLNO30ya8KRtlrSZTmXzp29jm1TnK7JzGmew7zuw4KjI+koPw5KygjAvaWlQGGttey8KfPxLOZ+7PThnSLc0wyYkK6azmVk/9L/2sUz1UJUmr+0+cXtTeJVyju/3w9LyW0cfPfq4Oz3jbdxPtzhPHN3fVtvbj5dfUbHWoyt0fXj2wTt+7Zm9aO97MZb6yz9jPYc52tSVPHtOlaK9MO6QyfkZ+zGpX5QBgjs3dNc/1zfnY73wFX1rz8J8xtmiT5Hh7Ogy6220/VO8SYfGK3QCiGIEMPZW4Z+M3GD46Fsw192YS0yHOH3RPbQZ3n3JHndtjLTsEP/Z7ZKIIZDD3jWN7m9M133w/+TjNNlIZJBRRvhp4t7kjk/VzIG3qKlKXomfMrR1TnKXqMnowQhh5+2rw2dy6KD2Z8SBM7ePTNNK43W/deaAWJGHooQiRdssQJkcAzLcgs4QfeydZCsRntt2b46NHsnv1N/j0dfIXeIJLQrXDMJ2hfk1QwtPs0+PvQ9/0bsAbLyZfHskebz8m0fhlJIfJrEdS18bM2zVJqFfX1301zhEgy7rFv3NxdmPWCepEm5Y+u49+TtoROPrh265fYbQdsew5x592qxi1bkfIoa/sZq7RtEijkBvs+TLOetNzAuo/7MHkOLSZHeT/3LDBKm+OTrrZvYYat0ae72E6nujSLn/gPZkHw6FmKkVdoK1ykLh8/a7J7D2lUxu6wR8+P4L+fUtYYzn7dmd74ulrO+rqawvuasTWj911RbQ6s0n/d37fQ/erQ+6q5FeLrzqJ++bm9uMz49lB/y1oeL3/LF4cbnxrvNZdse9+VzUV3NbX/Zf0kc8Lwa87U99f1otbXQ+uy7B/yl9vTKF+zFlH7XxZPDmyBOpCKlBaF/ExJeZiq1aOdgVAeURF/nR6673Wp96FT5tgpMI32gft6fre9UfZqSznlZ1ExHBizDAE8BavQVlGSVOalFRsvleVAXi7Neykpyd4E6w2AXRrjeQgzvNBA8VBykERg9PpLvw4OCAZ+lEwEluVCi7Tlcc3Vmcvzq9vLW+Oc1ETGZRHIyvJofGTayXLqns90INL6zsZo3N0wFScbfHhnZzMwvDA1UeQ9fDcDI/mS1X3FKV1xEDr/s+l4JYg3c0CC2Ewc634KRN5hoQj0mDUFEcxu77J+eeukbxYvqyKFvaLvLkqLi1gcBM/m48FAW7P7sKgmsrwQGhLz2iRZxG0aIQ8eMxGuKwQxLW5LKItYHkeHhCSP1d10MFQPmeUCTiBcj4uChy6v+ygLicGTCmctJDDojrTI0Em1D60IOlNlXWt4SJOOfIBxDzt4l9IZbmBIZwOdRg4Cr0scC1kHuNYzB73Hz7GFoBs617LhEavZATBMUo8qgHzaIug6uYSlY1DHB2/yXRxjP4bOWi5OyrACkKgKahQXvkbxkONugydo1BAdtvDdMy+GrqtCy4duSsKd9xSG4JVAGEGXJoJoxs7eRy40Munx0QDUIYKuXWOsJr/G4B0/Muar9zkAgsKPT1RUfqmK2k9FV/rBRtD+fLSD+eleTG+U92jlUwdzZzhK0OZ0hCBmfZ2OQcMZsUMjiqrugNHtPziKApJjbOG2nYHRXV+ZhwHAwwxRFIuXrVEoulSD9iDSKqzpvCLSEUtMmRmDFkjYCbPZzEOCAot408WsOIqJn4Xrhs67SeA5wpVA+90tdwlq4MVq+tTMv5+IQpdXs8u/nF1RHKcCzSERCWel9pvYT4V7iO03Y9eJJ3q+vkZL+l0HwOHFYkqRYeUye/FusYspSvATb4lsACF337RX6TDcdWXLabWPvEyGvWWRUo+Lq0skndhDy/fUwaAU+71EwYqFMxfbdvRQItUbPae9X+zQmYXR3/AzDa5IePq+YJoz3y85zMFgSBKEwx6FaZRmLNPZyN+mc4/VjtMMpPXNHDCqrw0mpYvue84I0T/keLReLXe9zYHYYx9H4u0pC+KAhCf2B17Pl6LngNAdexPeL67hySDOr87OsrVnJA1D80NnM3u2LSjf2jghc1SAtXNmgGTOEX6f+iQrcp7UwmL7RakOXutVqTW9zpvC/YTWe9bBmaZSYqmw+162WwJN85Bc76/zqnjnr/eifF3RALC3wqPs1nsSa3zt96SmHxivzkkhqdW5zpvia3CtFyWWmtrvSSwotV6UWItpvyexOtJ+UW41ofOu1LRZ612JWezue3PyUBCiiZWvzCR5+0XxOevWexHyGttaJd+dWL4nZgSJmeP2e1Lzw91XEyw8cGa8OqvenZ7vp1egMrO07Rfldu213pWZx61fpLMEU1py2rcqO0hSPavixbyXM+VNSnXSe/WmcrkXacs95T08kWjRck95NW93p73J3VbOfpG2u5PeQ/a0F2m7O+k92u5OerFod6e9m9c/U96l7e6U9/KGc8qbWcM56cVIeIKt9V40sYhMTI2iJZry6vRknF6as2ZkyotZUyD4IhlgF4dDnaGLsF7Sg4fCPaOQNNXhAUfIzRDrj5LLwTwcyb5lB46e6J5LqYUxnU4xWdigI5h02Zl9Izv4TBO/Pk+6zb6LsItRjKvPxanE1kZsmfkeSXP5sUMzC/DytN9kU0vlQxNN0okKIwM0Stin/Ff6ixmH2KLrHKJp0EXPZ1vp5/kIxQxQvlCcrcMIF6AR0B1GSRqBQHk74S75CIpUzdDBCd107/hGGXihGYRhYgkYQ5zFMUS0Kix653GV+c76wQnS6AHH5qtTe+uZ35x9c7Ww3W+I3WVNbk6hTeYxHsqPeQUyL0OIGIBWQL2TFw+FBkCwxyJn8CJrzEuXWZYnai6vOdi6OP92yz0XzMVyMMbfnW5evf4m/7H+PBc5dmz8iNz7/Kfy01zUR2+bxvn32Z9z8bJIAvn32Z+ieOWp81aICvJtmdDV0nD1jTpkk0YxoJstJOZfJlixDti6b8dmUWIm61yqNKBageSO/AkWMD1QHwrvwphg4SCxqDsBPlt998mwgR42UWiHwJPkiJwH1YWDGsqiZRQ3sCkyk20ip/1ohTakOsYT8GX6tILwThNfdqQxxUaZf1XakNx/zzVR7uypWyTBHpA8cqtFUmelaCrUGSjrWXUWDhL7QybAd+o/tYaq+k+dmbr+U2dDZhQvCM8s1wpNBDFg1TSAX2ysjhKJyBQDtuqYkEWwJaOKWlhHPUOWhV0cQTTkQvYCz3dCuvtefEV+ijkadE2pNNqyIDLcRuKbDaWwLctTh+0hSxk4tv4I0T1Whr9X6JiqLHoqsmdm4YBeqaN/QJvXb1TCv361UQdffa0Kvg6erNLCA3LT2d3kIQuOahHJIcLIJt0NJelcRuIq0nleWz0I33CRGgsOpAkKVQZea6Rx/pXk1taJRoDGdkwzpE4trCAsfpx6mgWQSS6ODdC5DwFbgA3SqC1PfIeapIEgRH9LcRbnk7pMVS4rzEDMswyZyGIDhyiiUY1Vy2naUqmpDP9t4xD7NvYtiXPQIqaaNWa7TgOsOBlGZBajZE0k0ezhOBO7U1cqtVDGr86mipVaAplP4tgAnZERsNULsqzIlie+4WuaAaipnyEzRa2sPlu3DSnNc21T6pKosLNI3m42N+oTi2FNaYox7AFMEUtYU5dJmsYWySnMDoOwqSgL7ZLdJ9FdzGp9Kd4FGUZ0ICHL2AUtxFmyWYj5pk/h3U1jwE4fWdYDjStAykRi3AoCCyoTG1YQUiaOpSCkTCA7FmSR9r27reSTnoOa3VIFjurOQi3zaZ5/Gth5hq12GM6Ezz828Rtbxmk5gzLUzh+WzMl7IcSa9kzYdkpaMqfghRAbRCVhm5epVVvpG9/JCmfgOXCA5Qb9Jt4cwQy8iQ0BA7ate8Ieixy5d1VdvgRGnshXLH3ylFncPAyDHTPux5uPXF5s0bt5TzIgEc+CM598+6K9TpAfhZiSAYQGoMu5/jZdSe+KYJr2s488x8qCukWyfV8JOyG9WFgFcOFvNdAJivZYYppiBNyBzXxsUOnpwQI7rK7uIX9KMwurK2/o25K2W5vRq7XA5peyfPiI+S2yELgOJNVyCa6FOMudLMRCPDzutFaXBdzxqhlmw3KJHaY5dH29aLXns/pmNpYDA1YF5auwJP03hpUliVRwAGFUucOVwrAwLnA6sNLpkx1trjJNHjdD5pzMKNA96UPiqZzqSIwVJ1lvsYAKTpJQqY1d9FzKyz/J6iowCjoFxjQeLYzsqqw3XnYm93Ycrjp58zI7evM2DOP8FI7pW6FZX9NtVLdhmodHnk4G6K+Peb8/DGe9X949aNMgpPybdfhA/Hzdwahv3zXOb87p/08HeEdbo48R6fA3/gSGOxc6XzMMekHv4n1X3yXd+2I69NVufxfcY7/x13SwD4GNr1B8X/0xHeo/UpziD0Hi7J4df9/5OB329vEuq6eLf8GA3jvIifnDrhG8Z9/KUrX+azrYp8RxSYI6/uYKPXG3IvNwbp0v+Jp7o0QH5fe3P9Oi7haBiilSduGu8dZKUlpt0CfM8gMYeBh+QB7OsfO/FUKb/gN3ymEO/CNG3Dk+Cfw7kb6NNB6cezO8d6TfdEs7T1BEs6L0a3EOw/iCdsXN5naj9lzQFJC7BEzRzsOCyjJzQOruohTfZqHSL/y94+el4u72Agq/KGTlD5k62WZvFPzcsz+mW9eJBbY0yuDSe69NxwblCliJlXCw7Mz60ndQSECWEU5IFqIr63Q6kIxowOqUAXRA7kIbFGUAy7iHgB4QDKUoDPmbeZdtvQii5MK3w0C+yy+EfYutj8V7gPDkWTu1ElIPCF1iIYpczN1e/pzXYHnM7wN2Q7jsxjQhfHMOkBUgLfiBTg9OQCtzxHkdqI02qOWjgsEY+MB0NoIFLOdl2sJTjvkdUyFys/+Y9Y06kkQH8ATDN4iBTZhRGEDyHH64ZDEk+WZxAEhqvl8MMosEAwiVnReWbVKGAOe2fQO4YjfxiGGlAqGFxZAe6c2FAqF/R9HyCuE3CAzzU4yjO/mJHDZY8+K2pGwjJ9fMbBtbRDc0oNABQctuW7I87tEnMbCAVnKuS7fnAvErt3/CAbp02hkMLZ/cLy8ShIKt8w4YIukD23g3qT4obl35/TfyzXmdxHTaHscbXnDMEcSsRsguT5QEqdYnmrcwNubd376TnS/nIWYz+cCY+InU/Nlu5Xyd4LvTzffcuxYkbeT7K3IDsok/hk37XtViTXvZRq77xTNShO+8pEmqBDlPWXXQjXUkpUb465Qi+B/fvi+X0KqWrH2bJOPraT36UfvMyM6QBui+UIHN3FKQrcYAErnqhJVRkUnVwcHPIsomB4fkjZC8+GzsIoxp4JZ8R2R1q275tellG8iAQflxYniQxa261Y2enEw+DJcvwBtWFJBnfN5YnIuTTw/vCVrIO2DCxSpb65/J9zd317eTXdbBu02QdX+FiGRe1S8MKXSdqzBalRhAeDYOI0yqJ2znARkdkTPQwuitJAfCFLhpVRjLw3FMxszmNt3tuKNIcdQwzWdYRKZRpVAfI9KcYO4lRsKYtMOM+PFxxfGi4A+BPrMw3t/oEj8UWIy98ACWyDGtKeg5QMCqIk4ijDzg3Jjwh+riWHQ5drZcgct+uRhlzjV+OT833t5c5Zdbfrj73fBJRysbA+fZezFDKOatmcHampkIwrayLA5m7Qp7V8gnXVSMQpN3UEscttkFTBxSMGU2LHPN5NXQTJB24Z4JRgv17E5UUZolUYoQSnW7VHxG8k3dIBQZG4Nhxf4rSKzHyOHu+hYG3KIYv+HFkBdHc/b8tT9xtNRx6Sh5J134hxAt5GHXhUtaywITax0Q+d/mFBYvDFze8pUEonBceXFMkfha4mj8kFPiWNldSy83J7zAzhKI2TQAsv9I48R08R5Zz2KB9+aZ2EWBRyMvqDFCQzpkFnJr6ozEKR134ESpoTiWnk4RA356ffo9MDJskpLRBI0L5nD3poqDJpFpR9w7qYXxRI6nSYCB9RXsA1gjgC2bd5uDDBZcBili8MLB8aZaxaGE9miIw9HL1KDA9nDdg8O9zdvsLo5FozVDlkzXAytMZXhU2G4Gd61cAuk1GFR+SDkfjpnIdQOwzotPmsk4sO4xdwOxOKRDWrF73gEtYbjAAUuSkHvztziU9DzVMJIVv5JeRxlDA8t3FOxbMLBiCQwaD7QnUoEKXGkjDkqGVq/OTuGSJT/OnV0yEIMVW9pzhlQdOaS42a/egI1TI7hOCg2FD4i1ef0GEO0MEOs1XM0COOCJaeg5ZB3Aim0GmE0QxKmTwHXYM9wguHdAmdJJXyy9LjiEWEXNBwN0PEA0saMPwnCQo2OKZVoRWLYu8MBSNseLZw8ySM0OOENK0WDmomqkcu6DXuNtYp8uk8zu9PXRi9kQGqk0RI7YtXjTzcTPfuA/zx/vNAyUcbOzSKkxREXHAJe6ZGCKAdJ98ZzEeQBlL3ThvRwgxLCyAShzqcYkXD/BT0msJnN0jSjLJF1DSjILQY5m9yUbeDDzzA1AqLFSA7IKuw6J6XwBTZc4iVILshBD1/BC9ysNArrONkLRs4FcZ+8L3KrCBcqXZEXDavLhsjVZGoxycne3A+UFk5vxPpIZocmTSmw04rkHFDvcO8L5sL7ppbP9XyybQrQ/FaRIZHtBlGxHHyTUXG2zWtIapbmgNVddE8ykKKD0wEo6tsL6wm7+ZWuCeDBlqVimMcPAna3T9YLp89oliGfPWUBtoEBkei+MZ3Yhm0iz1rCaQHQKYnrXoolEembco5RcoBDZApHQ+TD3YCWOQEEkf3g/a09XBVP2L2fWd+3p8rlgovcaSiCJXCQjDTfX+TUcTPPcBwRk6Dr8i6akAAF6lx04oAqxgVqMQqceYRBHNv0gO8rv8ELBwtiA04G5wblk0eC47XY273olaTg4dgKXP0nDwbGD6sU1Ied3wRpo/NusZNHguGUbn+DIzdlHxYCLkG8HHsiopIlKusZwkmes8TLQYsjUiCHTInaD8moOgYsc5yADck6CiKBCci0QAThCdUDpQ2CdfpKb6ei6iEI2uxbMVqPz/hgAUrZJFpKaQLApIRzy+dUZWENUI2a3zc5Eqxfbi7yWxZspbmjHdnYzc2GDYpUHlvK/8++Le4qKUDV+YON8WdYa/TV/l8ZDK5cXi9A59Jf/Ij95gZ26+POLHz6/+JEebcVW8sPVVfblV0+e68c/FN/+9Pnz5xeHJAl/MIzHx8eT2HHRlhANPOIrGoSNPnSCaceaPvlVsWyXvZZEaf6lY2efU+skt3sSYxoUobrC8Tb7mAeB3zmR94hIN/3RSQ752kt8sresDCi0vRbynz5/jj5/9r/66sds+p1uHYi/ClFCC2T24Mn/pf81iud+NDpa/5T5qeBMvEFx/+fr//78IsJe8IBt8tUOuTGuH7p4yqb5Y/LLf/5X/XUemaD6Vgv32niHUpc6l7yxj/9e/Pv5BV3332PfOLEiq4rzF1ka5ezUKt/Xxen/9eLrF7eXVx/fX55f3v3VvL379O7y2vz47ur2xQ8vfvxX4pnPn78qdt/89PnFq5PTzy/IN9i3AlqBka8+3f388rvPL/6VmKV2ieHCLnnMRx7+qe+GPBpl4YqPQZz8me4r4fmE2i3iyTzfWuRfglyaelFZJw+R//1IYwTXBEaQYzfcZtBVOuYOp1+RzIQjGimi+tLo2gkJ+2xXzG2Cwz/9wz/SSQTSQ8bRP1G25Y/k7//ztzRI/uUf/rFg/E8Gh1P+PHnx5UvSiBAZJJkLlrZpO9EPJWD2Dfnin/IvSLK3KFWpUmaH6puvVCUvaMIa6vmmVnE1BWgGDFw7S7HCaF4f9Z5jZtf6ErR6/Y6ZHcmXruPfZ99kFWY/h7INVLepqLLw5bG4E06hgaIPE+3g/dO9VUuRCP/BOzOL9liVjdY0p5rcxLgGWJ2p3l17S2jKrgtWZKqM6HSuqKCQ3j4KQ/pJobNaN7SqK/Ll1e3qhPSvVY03ygQxr5AoFiNUCcxjARZhWJcrp2pbA3qbFzPWILiqp81rc+ei+GDGhzSxg0ffTGMUKau+YxpO2nHzKaV2o5RfYa+uJFje5vTNd98vVMUeFFaxbScihWZUFt48rHhefreRvXlzeoYWMWKSiinJl0bV2yo27YMa2iZuHWHbtHbwadOzQJoN60xFDtvhfKOEqlyGPdfZ5vk4n9xVV1ga94MqrLHzydcFLBS1mUJ/0QlnbEb7rRk+0ggodvY3+fdUZRdlPvSPRj4c7n5dbI7+iJID+ZhGDtWZpKRW+KGcrjDKgXONueBURmrdYY/uT8JKJweKmUvh2YG8yiwHjmVc588TJ7GGrLRuKngOcZED4Gzc3F2Y9UWL4PBZc1ygm0QHcoO9CiPNXoxFdwzGKlIjHygc6PVz+d4stQbgFTidqtgscr0CLT1T2WUJ2R5DlUazqRb12qiZ+hCfYnOsRsfJdpNbWEk+H7UHrS9ruCL63Ylrz1gGmNG+VXX/Kg2c3FrrrEZuYLl8sNHrvF7uEh54fuCtd1ndPPrOwJuNAKsCrw+AZBeXCL8+xCRb5JREYRev/PaBL3tvc1aU3W7XrZdPSVrVFw/k7mwFn80kliH4uwbYhVCOc3FvjkLSXQtyrAcKv2QiF9ciQKRypuM03m6+PezLJgHIY+XlDT0TAAlN8k3ek1JDuQUPkS+bWV0J464FANIZloksL1SYLyp8OMJV06+Gbw4PRnebRshTSbgyAEk5sRRTzg2AUba8VCXhAh6MbnmTkCq+JT4cYWK32DSojHNtAo62hwhubEVOWFw1r4x9zxKciDA/tqqMeoEPRhirLYwYuDDibM1OKePKAhjpXRxZSotjZQCM8j60IqW1XmUAkLKj1MklPihhM7v4RTHryggY9cNOcY6uDABSflLM+AmWsLNRWgALeDi6SG03qcSHI1zFoFRGubIARpqeYrGQysmBpgkw2q5lq6RcwEPSrTanqiKcG4CjTDq1ShkX+KCEn7ZIaUe/aQOceH4LpdoJDpYtOCE4xn6stAZsmACkne08UUu7MgFHW3WXyQXvMrmKu0wudJfJQ467DZ5Ucm6YgKMdosNW8cxj0wYc8Vhpl6+AB6MbWr7SsVaJD0d45z2FodquSNMGHPFIabNYwEPSNWNn7yNXNe2mGTD6sRWhxDqESGknu20FjjxeoNZuGYGjrnbuNAaeO43JuK7aQa2GcWUBkrTiBa7aAhhp5R1U+O5pqrx/msJ3UJUvBsCvBTzYSGluLvHBCD/agdI6o8RXundH+HGBB0Ue6R8ip4ETpuxmc3xLYhdbbyd4EnjOtPyWU6Zh0I0WkGg6MTa/O9PKaptJgTKdhuXFTmwG2enQMnDkTE4syBkEadgfy0Vx7OyKbfwQHNmok2k6angOwk73Jy6uGp/pwBJmOhEiCU9srzqlsQKak8ugMj9Ilo+mzUN2qURSc42sk21ODJFCFc4MKglK0mnj0Q6XCohPRryh7O0Sj2Y1VHmOnrJLuBBL7BstoHm5kf4nwU8eAKUu3IwsQVfmXDcGINWEmltcANiUOCpzaBIErnVAjkg/bABCpjc25LMivkIeV2FO8a70lAW9hyzZpx6gqoAjBLm9ZZlhhIujOqAk+9DCRWTlgcY2CBI3oLcxTBlstKNxTK3O2yiTaodahtFGM/rgKqsMFDpTvdAKLDDfCY7RA5xYbbcjHjTC+oISbAJPJNo8xtxI8ikFvcN0GHmGT7PbVOjgBYJhDxAisaGItQBBcmGIonjijOloJqxxQQsLOM8G8AyiEY5xYk7e+89g2EYEqWmntGokDaeeBs3O9ZeRl6Z3/GRGN8z0yYJ3N6hMqnALPxgtpGqY0YWf2cFy2ojmAU072TBGesDG3K5hD9SMN4od3rAC3lccyJMQg5F2poFL3nJCpgsPmyfBCTPw1+j5DyR4Ea9Ei8qsjJmUXbQ2p2i1RZVlqws/t0Yo8EhPL7siC7nqOLdtHFNl0HL6nKLV8U9RGXTh4dNUGee2jaXSNI9JBJqsJt5FZ5un/cSIDAPOyol207htaymn5QzAvFanfNbCK3FfQZmZ3/pW9WuQaACtdedUGZG8AOoCCtepCDoWgKqwKvy2StbTzpnzY7+q5DztUN0458m72gU5y+5qn1vhAfbm6jDwM8dLTRe1e0ddE9C5UTHzhgnoPKmYuSvPfIEWpBl+ft0BTZPJrHRoApUJ0QWfm3daUfsB5jd4nCfMbgxQd9q4zbv2INmPmDmmEVkr34C5qGi0uuCgKQvNto+uUS3Wu3ti1arM6d+FMSs1emhVGWPamVu39S/ymLMVhydi3JzOdUV3qZoTYVMwAfKtrD7xmVlcRgmcd2hxRnTvBdPQIhEcuTlOgeQhMxrVYu2LX9btjbW5zCr5baiy2PcNwGyWqmoR+5n8RDI3XUKNHvJtzKplDBmd3bL37u7KtvyCyxkxBJw6EU5QtMfT9i5KJUnTEnA6zKqmhBIAbhNh5Y8wCOYtvgh5vbQCnm32i5Tj2o7OPRBOpQ2YO9sbXNVlzhmbcmWYT9iiu0T7H6YrN/phOq9ohWlVnnKooyo94bTT5E31ZW4LpU6OL5C3WhfgrZvLWlRm5bcWUpnzevBzq6j23YHZ1V6KWddGYLkDTFQKkAecqmwDh5HzQC+UmlNIWfxH7BxT/dXO+HBOKuq0HryKcqWWdW0ENmeC02bga9SW5NcrrNuIFFc8NG5wm+b9HKdxKK+JOjeHF3D3OPLxvDEXk2aNe0zVVNPHc8pN4ZLyjG0bFTblwGnWuDoV6+pS0ZWLdsVjXpGpYOpDrk3g2VmkvoM16/HkUYxUMe7YACaf3zGilHtlApi62ozSNjG719AGnlevdFmz0I+qXahLJ5BfqlAQTWDANITl2UXWqGVIbeyi53VbhZzDrIKeQ5SFvAacWyPlSCaKvIc3Hj27fnILzLKDfUzFunDznKJSeKQozjXgscQEOL+6vbydcnbyPIhEzlwOvD3tYkTmdgR62anjTqzxMvkG1VJFnuujziqDOVxxwyssxwboLIrJF3rjcIKfpg16GPzaiAD+o5ULqO8KwHnUstg93tm0myJZ1JqAs6h5YZrVy99BUWsBatT839xd3w7dNrxsPRTEmxnOznR08miBOCsjBDEZIkw8scdi1sBbqqWfdFNy3w10esOZeB616YnifuE24rE099izo4dJoRJEg5QOvD+7u4YnR0/JNDfD3mHpuCnq6zF6FVu1B3DF0UyLx6Sykru7hZMNGHrIRzNSaDOfngXbPqE5sYesUY70HzzxS+7hnU7N05uNUOrO8TmFyVzdxZvVqlIwKFIgZMw99nE0MZozy1MNvPnkps4nsohBRIEpgcydi+IDJLUacT7ByZEWWNxk4yqsfvC0WV6Lrb5m5oZpE+oNn9DGaBwdMnNBkW0hAmUuKG6ygVjmZi7X2c7LXAQgI35+dXaWTQWgeZ4geAYL83iGBWIuhQzsjD0TWV44MRNSj9P810CZGByPIExfYmwRkV5G7DOxvGm7XFs8CpAZLGio9Pk0CpTpPOzttN2MLRoFyHQWGCJN8Nw0Ka6en0+kwpnOJb+ffTaVCmYOEyeAIJKjTOdBL8yeTaMAmcGCXoM9n0aBMp0HvXJ5No0CZAYLeivxfBoFygwexT2386nUQHPYTN+V0mEjvfekz4be4jmbSQEynUUQIoiOSAUznUl2S+hsIiXKDB7RtNjsbRrRnBskCEAE0fJGc1teiKI7t9TmezMBeFQ407kA1R8AtQdQlwigR5TdrDebSIkynUd2Yd5sHiWKytsTZtxdV475ps2NUZ3ZKlCNMnfkOJtIBTNjzHZwADxSoswbwc6nIXe7LZNFtoUHTV07aJNpYE2+D8kxQbzTBpruoRn3zbXL0Nzr5rLsPy0kZ6cMzbmkI5uvmHzpXTu/zL3zjnZakLdLfYCapQE0o3WbsXutxWbCjrWB2SmAVJp1HWCBMHPdrcNnyqobe9ZsNp0CZN6s2WwWeG4th6ffAt0mIn3Z8xAXsGapBzd3Pm82owpm5nweABFHLsoucz5vNo0CZOZ83nwaSC62M3s+bzaNAmTmfN58GgXK/Pm8+VRqoPnzeQBs5I/3MOfzZjMpQGaxAKtm21hz5xhn06lgZs4xziZSosybY5xPI5rZ648g+inR3H4KRHUytyaJITwRz/bEc2ztADqwNc7sWVcILgXOXC5w440+3twZ4dmUANofoO4+QG8/m8udP2AuUGbOCM/mUaKAzAhP2aEUIcJwyg6lCDmuKbNhrB+ezE33EveCD6DsaLZKHBciDnPsmiXcpMn+zJlG6RkjF2iUkEYHXm6zIZfwlLwoQVh+6+20ONHdTIJeWoFfzG/JXjA1gFnd7DQJbighMi9SV5khMq00esCx+eobezutnWOnTNsbRiXE4NmfktdkhG5O1xVa2Vct9BU1ZH5z9s3VmsnaIjGpHplSOJl+oqxq7vmtaYCVZ8c1Q9YA6lImtLI0HrIGJITmEzN5DvEiQljWAIUspmEyfZi2rlHUWxEMpa76E67SeiYAS+2YGUOABkzXaNQKXGaaJVZ1Vpt9Harc+WRmUlAHQPi7OGpcws06rJOBejuQPkuDVwk5n1u+/m/iKArolQw2njapN0KVbWE+86whgCZbgc7nt8MoSSN4ik3cpU5shVGQBFYgO/rt4Wxd2UAQw/4lWCC1ayHNIHhGE3iNptnBGH93unn1+hswN9WQoN6qYQ2GmTV89+ht06kj977bMjRQj2WIRht8DT99eUQPcKUwQwP1U4ZotMHX8FPs2PgRufdgrioBQb1Vgho9E3r39w5OOLcxyQZRsFN1T3BTdVl6UJlmHGLL2U1c9Ol2BAhgPnFTTd88GWxTi83XLJx1UJoEezx7Qp94M/NbhF2MYpAKsYQkY/6dsze/7L3N2Wm83Xx72PuTj6l3MkCh3ujQN0RsAwx3SzNeYKcuNqspRGqi5LKETJ59PSo/RYtpIY6c8IAjJNIfhzzzTy8WnhePvKZeXUUtGXx8lSMrbZ5T6vGG8PKK5hbg5HMJDZw5m6bG+M3fQFWjA/qQCQpFENCXY9irLcjbkfMgdBtDv+HEtlgQQoD6ZyjPEw6Tqp9ctZFLKGugAmxuqO7w0YPl1QCcfbGB44WkuYz2W3iabOyjiQ5YZIAp5bztjqLaLMCgchMYrwaggtwERpONfSyBmGJsEcGJyH0GjDtysnYh8LE/J4Io6RtvsZ24sRmnYRhEskt6jKUZOqKAWRh0KnLIskhvPcqvsZ6Se0pXG02/GX35Rs7fGDMOsg5Ywwee74T0mu6JG7XnSOvYBlIWxmidFGMZXmUyULrTMuDLUuzE20YEPVjelFvbglnqpslhRc9hMi1qkyz/tjnAvLychq69VVaVpPtIvMyrtPiXFx3XtgBSHmFS7U8MRSzFvGEIgLZlecvQbhiCoO0hayHeDUsQFQQu9s14yhvvLJt3zUFIOKBXy/i+aQmG+Ob1m8WoN2zBkH/9arMY+YYtAPL7pWqZPWgtg60/QnSPl6HeMQZAPzlEGNmOv19GQM8ceJdwiV5B2xx8l3ABDV17cOnwgNx04oazKelQm9Njua10TX9KhLIVnvEeB4MaCOa5IIn8aQHfBtOrltoagZSGAEtMbmXOPelyEjr24JUUkZ8W1FJbBFJDOpTFcQPTxiH2bexbDgaebWBoGrELp6xw2jZ13MTxzXv8vIiwAbPgughwczSwnLK+YSXaSD3qPOSzeMtqaxsG14ZIt2pBRaU5cB3exBio02R4crFShVXEzt7PNsgvqKVlE1yRle0eWFBObRBOSxIhPw5RROwvr2vUuFKNh6l3CM1XeJh02ZCkvqXqvhHTSvUtVCcOW1ajbvnmeNw6nMogRH9Ll27SmEbBNS2faIOGVaXXck3CkF1VypaqKNlWj3rVkTViBp3ianiyOUPXswg/4zDrjOhEPVPOj/JzO3P0r1rViF01o7wFBHXMqRpNLKekNqh6VmE5TX3DqmeDltUGvyjdG/svJ8iTi8HHV1G0sTQwP03+Reo5lk1wRdNDKkxTMzHawpiS5jhj0QQaNKxG22JJxTSq93pfualGn8U+s+YEOQioQKuzGC0zMAvLNeb0iJXy/IHDVzaA4ceYYzKAR5ZNaGI7CsLnpZQ0zIFLgZ4mHdMBOi/aBFY3PzMmR9HkTNfEAfk20QK6WYEnq2kTXJSSdaIxRfCLRE10lCQ4ThbNeR2TcP2c0oCHHHcbPKnUM2QPXkwQo2nR6aYoKY2pkWFaXuzEZpQE8bRomVMldQ0f9bRms7OmxInlicqWGfCKx8Y7x4cdioxIaJoDlwI+phoTAjv27fWcF1IxLWa7SEWjYmq8q2TQIHiaOH6CI5/UYNnusYUSp2cUPpVKE4ulUtMg/NDwgK37IoTSUonUtQkvalk5CoWAr1yMCoFdtmCNpBdS0jCnZuC+kI7SluqB+0JyFK0hDQ6iF5TVtKlw4L6QopZBpQP3hQR1TKobuC/VKWjY02NlQlF4mQNyhaOxzAx/17f8clIgmE5GqXFeTh9tVW7I8kINabDQtQsdNP5j3/GR/Yii8fik/TjrAXlt+eCQmVnpA2GlRCN7vZxobGNND4+Y45BcQTpBbn61NBC3Lqa+sStbfGWKXEd+0ZT04OamjuxNKWO0xK870S6yomN5m9M3332/bmzFksWkYlLuHygwygLTxDymyIAV7ymZs+uLIps2MedG4iux6LSoVFsqSrICXqMZHUpYL125hHipaVverALipVXZqNFmZwcCtUtjqSVNDrMSDoKahxKpVX4OtRIOghpIpdemd7R1ntw94iwvlJWI5GXi6qsO72nz2ty5KD6Y8SFN7OBR/B4BkKqEEa2zTym/vxoqZFsff04mZ8BV0QaHlAz8qPxgyhqlSY8EnlF+WQlcRuSTTeC/m/kYuTE7957w3hvJwSFDl5C4clLo4F2EMd0UMb0uyzZWzM3st0EaWSA3qeT7POguD4mqKrtLvOFJo3SLkcEZOT2jhb3GDpJL33JTG8RPpUJTcicOz1UFRaOLDzBVXEF6YSA3GSFNurKgRyU0kB3uceTj2Tcr0thcaPr1it2S7LiOFfjv0XbajXrMlE8c6759Ny1M6c4daJQeMBrkDbbNxa7GGnDvL+fns9zagXt7c2WeX52dmR/ufp+BO4DuB76ZLcpMy1vcbEHTTU1GIG42mr4xailGaXVKVhCShGKpCQI4VYVhZcI8ZEVScRLhpFWmlabaKtIKw3OFzailZgNA1pBX2LtC/rRbJ5iJe8AoNM/UlMiCrFHb0PXuxQFvO3A9UpQEntxVl1w/F+yMGhoiQnkUEMO+1CYSYaZNcACuNg4jbKEE2/n2Z0f6UKsw82FTEPGaH+gh0j1xTqiGfdcAAOefiambu+tbJXyb4CCXc8ZSy6jCPEtgAI4ejmPSDTe36W4nt5lTmG3fBATvMDWzS5elt62I8+6ZAOL9GKEwxJE61k0DAJzLhlUJ3yY4BNco+EN28VWcawMcgOvfUpyqcWqFDHIFhxce1NQMNTQEzwRZ92Y2JFGT+l0DAJxvKeSVOsodfBAvRxh5KpuLngWIqx1QfK+EbAkMwdHxVLUJNfQi8+vsjj3kUK8JOmu7QauHCsmwCzyLZdbfg2RXAs5ilTcykLQqxHlbSFoVCCS/HvIsnrTugM10FeI8XnltAUqsgtRp80l+k8r0RVrX2UYoElkhHvG2RcbzCaLBnIiPZjm90GMUtIwe8rxcUV5XBMqxhTqLX3kaAZReExSEnXTIJmGKEwM0dXnGSAHFBugsdsh19r5s+EUuvRbqLH5b3/TSeWvoXXI15DxmKMZvvpl0PJxPsY89jytJjtQzrUDuSCGfZxsXgqMXSMWgFaVYwAIxNCP0qIhlCQ3IlOSjBxQ7D0rSnmVjFvf8VHo24QbKt4M7j6N0iG6BrsW0GNxjfR/T8ULYiokND8lYRXU6bGLeSNcK6wAkkhdccjmzwAHYKqgIusDzWOaRHMwwcGHzQBd43uyBFyTz5pW69CrEWbw8m4a4BSVWQ85lBl6jNzDncQvjCZcu8Om1YGczxFEUzJseZhGsUGfzo6POmfPXLII17GyGSYQs2KqvhTpvlIhsN7Dmzaj3Bok15jxu92qa5Q7uXI7g9UsDcya3x8hJYHNeAxNkdkJRCrPQZ/GNCCLpDZkH7M5e7++yZWDPmzWPXdPG23SvhC0TfTZfy3WgJ4PasLMZek48b/Mdi18JOpsdAX51pqafzYYHYiwbtFGC7bTQjIx6Kr9PvsxL0NOpPXSAWQzYxYeJcfZH5lfg6VW4QKmtKJkBGUrfeyeTGyfebjdcduCzJRMdim9xv1G5+870AzML6yZ156WMhFGDUKpiN0gm3oMuo4VhBkxBEkQEVhnzGh6KMbZgq7s+NBTT3c6WiiEiQ7XEhuIqe6uJDNdpt5gMc5W8KVeG6qT7cIeZhuheWdEqsaG4kkGTKqoFNFidpa66mu/RIkZ20Y5Kx7Pm987Y+KB9IOiZgw42cB9IEdupQbVH+EKv2jOwIbmqmEsfNqGop6mKPcOM+r7yMlraBiH7bYr4F9Cg/TZFVEts0H6bIq7TgtgPc1UymTaAD8YZeHm4Dw3ZK1bEdNKtxJxesSKqJTZYrxj5duDB778ZNgHZn1fFGGAfQbvXrYhoDJoXutMwqkj3zUDP9qhiXsMvGEV0QjiI2ecdRtyNZh65Lv1bHVouPiOwc9YocmCqhh7FAhiCY+y/UsOxAAbiCLchgEV04tYAJtt8K7oSqjU0BM9sO7IanhU0BM/UcWkI/928AFODXFvwEFFkyD+uq6jkN8EhuFpqMkCBC8HwgMj/NqdqaDbAwbiGgSt1jZsk2xIehO+0qw0lGIPfYwg4F9ljC3m7nwU1TOyxnDRIZHMMvBAlLzcnUrdyiTNtwYPwpRnJRPYfaZyYLt4j67ncnqBGwKg9VYp2ERmlQu1KF9LUtAiuio5bMgO5sQVUMSwqURWndBYXJ8sqY1gFVxfHMLMw42oKK+Dsn16fSt3OM5F+aQaOv+JCD1rCG8f6FVFuW4BgnUSmHW0V9XUa4CDxHbepGqIVMghLNXMwNtgcjH1QM8IpcCEiYFpAq2BdiiUwDEdFVVOFDMLyD7Aljz7PP6YteQwwhVmj7bOcsEDLZih/H7k4S9DLx+GO+fV4Tjvqx2S5VzTTsgebaTnc2zslFEtgCI5k8KuuCW+hQ8Te9dS0jgUuRCTYHFHlHFDfBARvmL1zPa4Tts0N8HutiOBrKIbYC6LnIoyciVw3UDNdNWAHQIFPhsBxYN1joJ0jXeYdfAjGDhk13sPEwemxrbEBmAaOmgJW4AIwDLGa9rTAhWAIcza9RxAq1mt4b8Wv5t0QNsyxhAbiqaY2rZCBWH6rjOW3UCzLWIJKiDbAAbmqm2PqWYBknQUbVMq6tADBOnCfX52dKipmDXAIrpHzgBJsIsvCsZqmv28CgncZgVIJ4wY4ANfIIe2g/eqNmmX3FjoEW0VzU5O2XzIZxgekZpdVCQzDcfP6jSqWBTQMzzNVLM/gOL5W1LeqoSF4Klrng1vZy2KhIOugpgfQQodim20jiVMnUbQ4wjICxT0I7h2Frq7ggfjSq1wxzAZxFt8aHoBvHWZcBd0WOgRbx1NGtYIG4PlASoEDdHayS7SBDcBU2a4EwH0IFMq0IjWNQhMcjqua0t8EB+Maq1mmaoJLHmABuSmUjD0gznMo2MhHmBmw+/WKA/b5BiCU0jOxPr05Dna6tOY9ZApcS7FF6B4/E05OZM6/0pAvatCmKnXxsx/4z8CrcoO6mtb0PQdB6cOfgcj9QXETx6fBB8IgBu8QNzzPtgSvJIxI5yVxHtQraVuCV0JLHanG6UQXdP+JoaZvDU5Rvs9clYIaHZIx+HJ7izHkeYtW5ArAQCUM4j0jCvj7CX5K4gVqpHGL6pQtU675VtUpVF8Hj1uEU0bAI9ip64aIChyOr4JzDg3CsOcZijAVKhY8G5yB1zyrcApFFlRFu2UAkLfzRV2hrMAB+SZRainrOdTocIyVDssUjL8ekJuqI1yjK533gLwHdPSR8R978y5RkARW4I5OvvTe+vLyET2IxPHovfn725+n31P6Ngxdx8p6B59ICpPWFMtGAWFhfiB/QUw+EW1mAWc+YnQvE/iyTAcjd61BsAyWXKMwYLCMARS5BqxMgZtDH6iyaDrEf5C6PnWW8wtba0yaXtC7uX9Fvk1U7iFy8Be0M/MLv22HtDzONk0Cqbjlwp5sUTcG7QLkCza2irwtogkmrzOxTV8u2DakrtK2Um0rpVlpe40SXsxjXIo3miOepbXWeYaX3wy0o1doqcgwFWtjyCRQfd+DVpFFOGrgWq8COr9YaDkptb01cvhdlOLbBCVpfOHvHR+sI3Z3e6HEhV2+RsPYGv57ayUpIrUUWAe2wFPT+yvAja6lRTzX0kr43Tkejt5hHN665D+qOox9K7MCRJaIqnrnFTgMS5VOne1LmgtVDRUa2BAcTRSqyaEd/NlcI5yQ/hMxQf7ak06UojwwbGqWAvxAg7kqKVs19Gwfn3v2x3TrOrFkFDMp73aNzGYtPe0oRXfivCODJ/3GdGx1VJsG5rH9zSSG7dRKCJyJJSNxinNmmpnL/C5CfhwGUXKLrY8FFVX0h2yBabjw7TBw5MJMTxLQNDQ7pzesZeNgdVmeaQmk7VbFuMAGa7sV8izxVbTdqmizTc1WUO62VtXlaOCDcVXl4gk7z+cGeC/r1vNs99DcpZk4sqAmtUvHlfuaZuaPtk6DEDUGrKwxJeD4yvw2M692/EaIMv12TGuxA2lA54+nL3QCXZTwRXCVlpsVSA+E7mOKAtelAVhCZ05GoK6pFuK/5HmDhQ8xq/obOFEwZmaMLcIheVbjzy46DGc6yrLxblZHkc23iQzEtewzq3FwDx6G9RbFTqyGcQsaKA8/k66bRy+gi5I0VJSTmTZg+KO689RIUJD1JLYYAYNAKeMSi4oSpAkNw/ZTjKM7FEtFOxIj20SG4Wq5KI4tuehxgm1gA3mNjuOXEI1vBBN0EsUxt0GQuAGy5w0i244iuAYDHGLXAUWNs3U9BXRrYCiqE0KrCnKFDayaQTq+M2tmbIBpCQtF03NiqfiFgjRLWCiaM2e9BlhOmu8aJhkGj6Qnn1+Mp6IC6OFDEY8QoaKAcIULSjSL16Sixuqgg5EGnWEc4g4wtzgsIUVy4QIESZewUDQfUWId7GDWlM0A1Sa0HvM0pRs6/RnX2UpPobSDLzvb338jnjivJydId9LB8eYEzXQrgTbG4WdNMBPoLK1+/+VqcwZFto0IPqk8fbatPEE1fcbt1iHDssB/j7YQJwriXx8n9qOBpsAH4PLtfzMQmXnt8u278zkz6mXqGY1EMHIvZlPrOWujNDOlhhxhvw1QZC9Av7Kjgj/pC9t0WmHebn0ZJW2LijSR/v1ycnJj05VMGoOPFtdb0hgg9+3HS+gSWwGbh0eVHq7sGF2Lq7h5zqtQi2zM9KA124x+2lgy0DW2An6Gz1lVpkLClQEwygmK9jgxM+BZ4yUe9Z4hMAn4iQxr6Ip+Dm5+d7r5Xurgv6yUQYOTxiiTZihBpjU/vn0P0xubW+Y7cM21AJI2IY4mHGjlZhu2FYAFfWb2Ib7O8g7b6sDXM6PNzMgro+lzQO5La8pOFm6a1MjKEqA2YbStrerhdvDV1sKeMk/0zYBVydXMTRmujVSZynQMGQNTE7umbdmzpsDHE6LG17UFWWCuQnJ6AKAR6jcItBM+I5UbfYQabNZ0VXdICUOOgQrCct5qFoOg3DrWQpl0ehbNFrTpselsOpPUWih05uXZ1vBxpu8NFj2ja0GjxDinUd98umt+xvzmY3ZkbmYqPM4+elhrMQo0o4E6q3QWOO8d5MTztlUPk2yAL7Wnmm7qlp+TbnvG+YKvpe7lHPFIxseoIWel2ZXjb67Qk9QtF1xuTdClUuk/UpziD0Hi7J7lY7F0nNLGAnJNG9To21jKUx8CG1+h+H6ej0oUIO+UcEYTdymPvKOXqX+MHF98xzjTJzUOkFdqQKONPavM11Dns4fAPLLn0sPeuYl5fnM+LxUJAJBHCJJRoC2lPjvc966OnTPPFV00IL90YXtfLOmx22ffyuzPbOJLGKh+T4lntJCX8srVbn8X3GN/ZsenggHySoVntJDXGCtMiQE59HV/fsAnzWAey5+zOkhf/cE4/8Gg+6xjww48xyedQ49O8zrJ823mV+PhtfkYRPdxiKxiu7O5cyLvEUXYfHSSQx5nOJsebpvuerYbINSzzQMN3kVsk3ceSIpwF8BhGQ8xkCC+HmFBonQ9y0Ih2hanS5cnzGLAJx7n041Ls63NilBsbmT1aC27PF0WBRHqq5KWpxvtVqCZGxWhVx7YW4Fk0zSPauB54tEDgbn2bHPI0tgIW2Tdp6EZ4Zh07BYmzLbPIZ3PSaLQyeLELEu4b5tDViAqFXgPQYBWvm99UWKVSQ61BydKUnokKDtEt1I/a4QEh76HHG50DViupUV+TmwI4XT3VfZaGeOBsc7foky7liVb+aW5do0LtvLL04yYM+GjrfzyJJum5Vr5Zbn2bHPJ1qcn0pCep8a2uUt97kYGaN4jNOQ7KotyZ9uX66gsSrhvW6CjsnSjIFjQAn/lfDtAgZf8Wd9hTeZDDIQ6h4syHTxHKdg5XJTsCAkO/WoPxbKEW2Y5FGm4qfJq1VWa4gECHNphECfZBasn8aJs23Y5JG8u3r67ujjx7CUZNoz26BVHVz+i5KDIuqDRcnkhjII/sJUYcWXPjO17c3O6+ebkzcmm3j75Dj84xHJzF2V27tK4LCODqbFbHInK9hiCWjigyKbey7e8KTBQSahDg6i3YGQb29RYIdkzywOWG1j3ZaQDlY5jG8xOoKoxeH51e3lrnJPepupsnVu6ubu+3ag2VXrRzkrwkulWWKS7SVWaw54dPairKBp26KlzhQayEBfkv45rUkuhm+5JU7DDXhb2Athq70bCXYRxlAR0bB47saJcOWz1Hkc+dsvgDkubpR12tHWx8cv5ufH25so8vzo7Mz/c/W74dChC+0XKCmief/ehE2STDFEaKi0uIemchgccIXeJOuCwewoU1jlVK55f/Go4lrc5ffPd90uY8tIlHFjliSVrbqZRA9F4FmoMFz51sU3LglKF+RCHnv2xyn009ENxIWs5ejfKc3Za0CDAOMbJ6mzgE4Z3Me5S5kiDG6HoWXXB8rAXRM9LFuWORYW958piqKJi7Fa/3tPmtblzUXww40Oa2MGjX57pY/xkpjFJbrUtuP/gnS2Roq1Ic6vUlWGMzLIVXKw7XIYKWqbvXW65JH3CpU06GOPvTjevXn+ztOVHb5vGSxstYsIvk4cOTmjgXXS2yf/7tN88La03dmz8iNz7ZUeRIaIn7osbOBZLY5btyvNny7LIPtP2vx2qM5ueWLgGXWgWhmNbYVegmIxJgsC1DshROi1TNot5VIVFLNF7M5PsFOYC1giQi55VWJK8ZH4t851L5ZWT6N8Jo9hoP/b6Sq5WbLaOM6DYECeO1AIymUf6F81GWeR8pfb6h9KXM1icQV/KXPcw9VJ266PJS1lsHv1dvowWgXlWND0QEGxNRs2oX2q6GsSCVV+Aps7e1CvtV+v4VFfZr2PfzPvRlz8vV/6z0+JLGesfzl6swaoPOS9lsnGCuGfSQ1YUvMM7OhYlOeBzHfbo40fz4831x4ubu8uLW/P8+sPPl7+YP1++v8j2Lz0gN6WP/R83+RdOJMM/yZjNtvac3v558+2vv3yQevE38+ryl5u3d5fXH8yfb66vzG+Jc1pcX8ng3b432y6QfPnP129v3pkf3l51/PW3NEj+5c837zZvTs/e5p8mId9c/IUB/Pb01STM8+urj9cfLj7cmedv796+v/6FCL+4JZ+lcd5dNMCI6y4//npx8/a9efvX25u78xblA91Z+RxHCavZHbSSbWAxP/zl8tz8y+XN3Sca0XTO2+avF2/fXdwwsnbmyGxPgumTAbFZ7AY9Oci7+OrPF+/u3o8Xo8aq16SiQ9x/dXF1ffNX8+P19Xvz/eUvv85NvuvfiGOu3n54+8vFTYtvayJriiM+3r41z2/++vHuetQndL7fip7DJJjsk5u3l9QZfzavPr2/uyTl+e76nLjn9tPHj9c3dy2Lp1OgP92R/3x8W8rIcxMrcRvTgGiymk4KnV/ftJ1mBcztIhKQt+8vLj7eXV51RNRTT5Lw/355N1QN5pX9y3f/Pr0ypOiAVWGRiGUu/XR7QdqSiwu6Xc78+Jfzt+/fX7N6KYN4Fz/fnG1+/2VWM3R5fXt3c/H2yvz09ubO/Pn9p9tfzbv/Z/75088/0zQSx8rz3EcClycybdzOL25vLz+0CeInJ/lIC/i74JG17MUzcHPBwad7PCYZ+PDu4s+ffpF649rM3vl4cynXmNFrw4vc8O6CNBcX5vXHrG9x9fb231tyfrn4QJq5c/Purx+J8DvSAzmnb97dXL9/L5dA4jZJ1+T95Xne2flAyu/lh5+vSSV3e3fxIfO2VL9pItnmi+afby7f/XIx/f3cbzLv37x9d3lddIbK/pRUyXr37+ZfLm5uc//+23W7uvt2MtTlhw7UZjMV6+Pbu/Nf21iy2enPny7fk27odQvlm7Pvv5OqhSjSsK9eSbWbLayZzmpiiTmr2G3zc35aQ8lRLIk9G8VlUvTvfN/n3rJY90npQLuztonIsHmP/Xz7kkNvmnMxinH1uTjY82XvkSY+3m6+Pez9vyN5XmCnLjarFWUqrXxIQGKRf8lLoo8KP8jaKcl80A/I4EuvxIC5HU5TBeNXxv1Il6yvw6J+ox8u6Ymx+tuT1DqplrWzei7Ivh977MQK0+7wIMFPL70z1hYIJQx2HQa78OH1yzhczLwboMREW6cz8xCxDsmJMKAbGkhWisYJlE+dhBGu9pN2zDWMvifZpDJcj7iySqVGYB6ONGrDU+SgOMbelqunekx7QdlZS46a/Jnin1srcsKklT3+oZxsrVsB+mR2vt5dKOPQE9zZjGqMs3/jFsMkSlnDfAU8bJQgcA4SieQjPzAt2iav5QHSUiTmLiKNphnmB2VWIkIcgZ8sHK6ZHQiHKEmctZKCzkA5X7KlhvbslPNlgbxIqgIcoQRfoTDrW6zjBIve3+PbWRPWbNpffbeQ/aenAQb//M+vWONmBRxIh8x3/H18glx3pWSoKGRdwrVJhNhGfuJY7b5WHm5g2QQhPWUcRUEUz6DioXuctbYo8k7ooDG/SrDLZeCxXq/3pUe++WlC33cmj+SQetsOk+K7ZQh0O98vPfLNT0UX/KX96s1iRJjdcEKHfv+SfP+TVJe8Z6aunLiM6keHatKXcWL/JFOdjtgIQwlCNKDjUOWak5KqYYFpsZr+lzs/eJl/uxqpgT5RRq3527J5q6wQzW4L9fK37Jvl3aWe0ST/9JvPl78V363oI6WsZPw02OV9eQ2Sp2U9pJqPjG+Gx6Yvd/S3l/VvyztqUXIyXhufWXi5K39f1XurkJQql+OzAi939IGX2QMvqwdWKK7r0JTxpH4zioD+PwJxg1PAw08egyz2vM7AY8NzwfOmgGeyyiY/e1OfL8ngDVvxT/TXk+zPpfiUE2Bm/tn0UNhm9v8KvM9fvbxC4U//8I/Xn+4+froz313e/JPxD//48eb63y7O7+h2sH86yV4W5J3vgj5xSG4p5ua7lIuQX0HY7pW01p/n12w9Rznx0BXEwyXgpWd5rMkQ7nsC6c7FmPLOzsNkFP+SjBLo8Qw6PE2mwLCHGfzXsumkyS/+9OAyOu2iL6d+GmP7ZYhoC8lsHAWQ2OMG/otkAFuuM7+sOjw2tlzCJu9/S2OyTtZI17WkNJzEjou2cVYiY+dsk5cSOznJ9wTbeaRU+sbJ3k9PGq3iFhUhUBvFqAHYeTp/6ISWs5MgOeDIJbL+t8T9b4k7mhLH2LgjkvxxTIrRSxf7++TwE2uD3RKllk6yyZTb5vP/W3L/t+T+b8kFKbkOik7wY/j/27ui3jZhIPxXJp4DxYDBRJX6sk2qtKmT0q6aliliNmWoNERA1lZT/vvuDCZLSaLgJms3pQ+BHvb5w3c+bJ99lr3RTT3R83dYcxdqsrt3c1nfzPSwIk4kNGvQlEX4SS3PIk+Bb8nQmJBICLnuN8pw7d7Lv+KugyitscF1NjDN+wIGTxMMFTuRY6k/iHdgGHLeIfP15CJWdI0mhWzAgBWVmRT5fIasM1yxilfeFhRPRfNcs4iEb5nE240FNH6cuTeL+wfgleAhSevGxPqS/pGX1VHUW0T9dwYRzTTETkMITKssSCZusijRsBn/k4hetinp9T57CLxJrUR+FPirs537nUQ7dvCPHfztHfyD+ka0dPYB/mlZmrihxJQepdf8Ne3LjqcFn4NQRDwD2xRP+aP+2sjX81ZTMGKi44npt6rxOZ/APbzK8nPaU0SnKvhMS3lzevZwl2GWOrQqZCJWHWwFuOUinSZAurp8b7KxcbZkpHw3ywPouFXvpLPKuJrPLBHfRPOsGsVVJVeTbt6CZcm9c8CpiTjzOOJwBZatf+jk8HDn/FOd5FlAn2rPTZ4J6UNTBzbWLshN5mb15DGLF1xFl+BFXTJqAtRnK1ogKU+e2NwkT2ocW9TAGBij84+4E/388stkdHmFO7KXEXOMofFrbGyumbExHEOK8dgoIYkYVTm//RwVKR6HUiJ5iD+YAP9A5WcppBK3H/I62JB6MFQ3G3blqccDdYMB+C9m3fyrzsKGuKh/ILfxttbOfwv3AqRUQ8A9CyUI5StIpZU/sEH5D1p9lNGn8A2V57vMJjEGrFLHJaO/HpLnRZqk0yhr00tq08KAQAb1ebQy1NWQeDR0HEaYsxj0Lr4NIgz97CrK8kQLghm4xLd929sVQROZDgBIAcFgIPk+md3fTbJYyHu42m0kFx1EnudRxyE+0aiUVZlwneIZcz2HMZ9qFL+mSlLZG+ZxqYeGMNtjIWWBu284erJxHc+lzGZ90XQssEZV2NQnNKRhV1dll2NN6T0PuikLeWBFU1e6AqO27zie3dWf/aLsClcTMCGhiwrvHwpwcw6IQqllKQMW+NQJ3PDAINfUqg7ekAZ+4FKy+GYsfgMoicih=END_SIMPLICITY_STUDIO_METADATA
